data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.text_line_rotation_dataset
        class: TextLineRotationDataset
        TextLineRotationDataset:
          datadir: '''dataset/test'''
          image_pattern: '''**/*.jpg'''
          image_height: 32
          image_ratio: 20
          inner_size: 48
          dataset_len: None
      batch_size: 16
      shuffle: False

model:
  module: flame.core.model.mobilenetv2
  class: MobileNetV2
  MobileNetV2:
    num_classes: 1
    pretrained: False
    features_fixed: False

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      loss:
        module: flame.handlers.metrics.loss
        class: Loss
        Loss:
          loss_fn: torch.nn.BCEWithLogitsLoss()
          output_transform: 'lambda x: (x[0].squeeze(1), x[1].float())'
      accuracy:
        module: ignite.metrics
        class: Accuracy
        Accuracy:
          output_transform: 'lambda x: (x[0].sigmoid().round(), x[1])'
      precision:
        module: ignite.metrics
        class: Precision
        Precision:
          average: True
          output_transform: 'lambda x: (x[0].sigmoid().round(), x[1])'
      recall:
        module: ignite.metrics
        class: Recall
        Recall:
          average: True
          output_transform: 'lambda x: (x[0].sigmoid().round(), x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/2012262317/best_model_109_loss=-0.0078.pt'''
    mode: '''test'''

comparer:
  module: flame.handlers.pred_data_comparer
  class: PredDataComparer
  PredDataComparer:
    output_transform: 'lambda x: (x[0].sigmoid(), x[1], x[2])'

engine:
  module: flame.core.engine.engine
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda:3'''

extralibs:
  torch: torch
