data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.scene_dataset
        class: SceneDataset
        SceneDataset:
          datadir: '''dataset/scenes/test/images'''
          csv_path: '''dataset/scenes/test/test.csv'''
          image_extent: '''.jpg'''
          image_size: (224, 224)
          inner_size: 256
      batch_size: 64
      shuffle: False

model:
  module: flame.core.model.mobilenetv2
  class: MobileNetV2
  MobileNetV2:
    num_classes: 5
    pretrained: False
    features_fixed: True

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      loss:
        module: flame.handlers.metrics.loss
        class: Loss
        Loss:
          loss_fn: torch.nn.BCEWithLogitsLoss()
          output_transform: 'lambda x: (x[0], x[1])'
      accuracy:
        module: ignite.metrics
        class: Accuracy
        Accuracy:
          output_transform: 'lambda x: (x[0].sigmoid().round(), x[1])'
          is_multilabel: True
          device: '''cuda'''
      precision:
        module: ignite.metrics
        class: Precision
        Precision:
          output_transform: 'lambda x: (x[0].sigmoid().round(), x[1])'
          is_multilabel: True
          device: '''cuda'''
          average: True
      recall:
        module: ignite.metrics
        class: Recall
        Recall:
          output_transform: 'lambda x: (x[0].sigmoid().round(), x[1])'
          is_multilabel: True
          device: '''cuda'''
          average: True
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/SceneDataset/2104090731/best_model_44_loss=-0.1877.pt'''
    mode: '''test'''

comparer:
  module: flame.handlers.predictor
  class: Predictor
  Predictor:
    is_multilabel: True
    output_transform: 'lambda x: (x[0].sigmoid(), x[1], x[2])'

engine:
  module: flame.core.engine.engine
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
