data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.doc_orientation_dataset
        class: DocOrientationDataset
        DocOrientationDataset:
          data_dirs:
            - '''dataset/multi_classes/doc_orientation/VEHICLE_REGISTRATION/test'''
          classes:
            DKX_BACK_TYPE_1: 0
            DKX_TYPE_1: 1
            DKX_BACK_TYPE_2: 2
            DKX_TYPE_2: 3
            DKX_BACK_TYPE_3: 4
            DKX_TYPE_3: 5
            DKX_BACK_TYPE_5: 6
            DKX_FRONT_TYPE_5: 7
          image_pattern: '''**/*.*'''
          image_size: (224, 224)
          inner_size: 256
      batch_size: 64
      shuffle: False

model:
  module: flame.core.model.mobilenets.mobilenetv3_small
  class: MobileNetV3Small
  MobileNetV3Small:
    num_classes: 4
    pretrained: False
    features_fixed: False

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      loss:
        module: flame.handlers.metrics.loss
        class: Loss
        Loss:
          loss_fn:
            module: flame.core.loss.weighted_supclasses_crossentropy
            class: WeightedSupclassesCrossEntropy
            WeightedSupclassesCrossEntropy:
              weight: 'torch.tensor([0.120725, 0.1242547, 0.1245886, 0.128166, 0.1245886, 0.1304555, 0.1219652, 0.1252564]).to("cuda")'
          output_transform: 'lambda x: (x[0], x[1], x[2])'
      accuracy:
        module: ignite.metrics
        class: Accuracy
        Accuracy:
          output_transform: 'lambda x: (x[0].softmax(dim=1), x[1])'
      precision:
        module: ignite.metrics
        class: Precision
        Precision:
          average: True
          output_transform: 'lambda x: (x[0].softmax(dim=1), x[1])'
      recall:
        module: ignite.metrics
        class: Recall
        Recall:
          average: True
          output_transform: 'lambda x: (x[0].softmax(dim=1), x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/doc_orientation/VEHICLE_REGISTRATION/mobilenetv3_small/2110051402/best_model_44_loss=-0.0000.pt'''
    mode: '''test'''

comparer:
  module: flame.handlers.pred_data_comparer
  class: PredDataComparer
  PredDataComparer:
    output_transform: 'lambda x: (x[0].softmax(dim=1), x[1], x[-1])'

engine:
  module: flame.core.engine.engine
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
